name: Java (API CD)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java version
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn package -B

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: containers1352353256.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      env:
        DOCKER_BUILDKIT: 1
    - name: Build and Push    
      run: |
        docker build --build-arg JAR_FILE=target/*.jar -t containers1352353256.azurecr.io/my-java-api:${{ github.sha }} .
        docker push containers1352353256.azurecr.io/my-java-api:${{ github.sha }}

    - name: Configure Azure Web App settings
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: intens-api-2023
        images: containers1352353256.azurecr.io/my-java-api:${{ github.sha }}
        resource-group: devops-project
      env:
        DOCKER_BUILDKIT: 1

